# -*- ruby -*-

require "rubygems"
require "hoe"

Hoe.plugin :Compiler
# Hoe.plugin :cucumberfeatures
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :manifest
# Hoe.plugin :minitest
# Hoe.plugin :newgem
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rdoc
# Hoe.plugin :website

Hoe.spec "qsomatch" do
  # HEY! If you fill these out in ~/.hoe_template/default/Rakefile.erb then
  # you'll never have to touch them again!
  # (delete this comment too, of course)

  developer("Tom Epperly", "tepperly@gmail.com")
  self.spec_extras = { :extensions => [ "ext/qsomatch/extconf.rb"]}

  license "MIT" # this should match the license in the README
  self.extra_dev_deps << ['rake-compiler', '>= 0']
end
Rake::Task[:test].prerequisites << :Compile

# vim: syntax=ruby
